excluded:
  - .build
  - DerivedData
  - Pods
  - .swiftpm

disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - vertical_parameter_alignment_on_call

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 15

reporter: "xcode"
